#!/bin/bash

if [ -z "$1" ]
then
  echo "Convert a subtitle file generated by dvbtextsubs into an srt-file."
  echo "Usage: `basename $0` subtitles.xml > subtitles.srt"
  exit $E_ARGERROR
fi  

sed --silent -e '/START_OF_XSLT$/,/^START_OF_XSLT$/p' $0 | sed -e '/START_OF_XSLT$/d' | xsltproc - $1
exit 0
: <<START_OF_XSLT
